#!/usr/bin/python3
#
# Export modules in CIL format
#
import logging
from git import Repo
import argparse
from semanage import semanage_handle_create, semanage_connect, \
    semanage_module_list, semanage_module_info_get_name, \
    semanage_module_key_create, semanage_module_get_module_info, \
    semanage_module_info_get_priority, semanage_module_key_set_priority, \
    semanage_module_extract, semanage_module_list_nth, semanage_module_key_set_name
import os.path

logger = logging.getLogger(__name__)

dist_modules = {}
with open("ignore_modules.txt", "r") as f:
   for module in f:
      module = module.rstrip()
      dist_modules[module] = True

parser = argparse.ArgumentParser()
parser.add_argument('--selinux-policy-src', help="Specify path to selinux policy sources.", action="store")
parser.add_argument('--git-repo', help="Specify git repository directory", action="store")

args = parser.parse_args()
repo = None
output_dir = "."
if args.git_repo:
   output_dir = args.git_repo
   if not os.path.exists(args.git_repo):
      repo = Repo.init(args.git_repo)
   else:
      repo = Repo(args.git_repo)


sh = semanage_handle_create()
#semanage_set_create_store(sh, 1);
if semanage_connect(sh):
   exit(1)
   
(a, modinfos, b) = semanage_module_list(sh)
i = 0
index = repo.index
while i < b:
      module = semanage_module_list_nth(modinfos, i)
      (c, name) = semanage_module_info_get_name(sh, module)
      i = i + 1

      if name in dist_modules:
         continue

      print(name)

      (result, modkey) = semanage_module_key_create(sh)
      semanage_module_key_set_name(sh, modkey, name)

      (result, info) = semanage_module_get_module_info(sh, modkey)
      (result, priority) = semanage_module_info_get_priority(sh, info)
      semanage_module_key_set_priority(sh, modkey, priority)

      (result,module_content,*x) = semanage_module_extract(sh, modkey, True)
      base_fname = name + ".cil"
      fname = output_dir + "/" + base_fname 
      with open(fname, "w") as f:
         f.write(module_content)

      index.add([base_fname])


commit = index.commit("Commit from semod2")
